# TL;DR
# docker-compose -f docker-compose.talker.yml up

version: '2.3'

services:

  talker:
    # build: ./docker_image
    image: ghcr.io/dominikn/ros-galactic-fastdds:v2.4.0
    restart: unless-stopped
    network_mode: service:husarnet-talker
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds_client.xml
    command:
      - bash
      - -c
      - |
          source /fastdds_overlay/install/setup.bash
          /wait_for_discovery_server.sh
          ros2 run demo_nodes_cpp talker

  husarnet-talker:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=talker
    env_file:
      - ./.env  # create .env file in the same folder

  internal-listener:
    # build: ./docker_image
    image: ghcr.io/dominikn/ros-galactic-fastdds:v2.4.0
    restart: unless-stopped
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command:
      - bash
      - -c
      - |
          source /fastdds_overlay/install/setup.bash
          ros2 run demo_nodes_cpp listener