name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  
jobs:
  start-discovery-server:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy Fast DDS Discovery Server
      continue-on-error: true
      timeout-minutes: 1
      run: |
        echo JOINCODE=${{ secrets.HUSARNET_JOINCODE }} > .env
        docker-compose -f docker-compose.discovery-server.yml up

    - name: Exit code of last command
      run: echo $!

  start-listener:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
  
    - name: Deploy Listener
      continue-on-error: true
      timeout-minutes: 1
      run: |
        echo JOINCODE=${{ secrets.HUSARNET_JOINCODE }} > .env
        docker-compose -f docker-compose.listener.yml up

    - name: Exit code of last command
      run: echo $!

  start-talker:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy Talker
      continue-on-error: true
      timeout-minutes: 1
      run: |
        echo JOINCODE=${{ secrets.HUSARNET_JOINCODE }} > .env
        docker-compose -f docker-compose.talker.yml up

    - name: Exit code of last command
      run: echo $!