name: Test a Docker Deployment

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test-discovery-server:
    runs-on: ubuntu-20.04
    strategy:
      matrix:       
        device-id:         
        - 'discovery-server'        
        - 'listener'
        - 'talker'

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy ${{ matrix.device-id }}
      continue-on-error: true
      timeout-minutes: 1
      run: |
        echo HUSARNET_JOINCODE=${{ secrets.HUSARNET_JOINCODE }} > .env
        docker compose -f compose.${{ matrix.device-id }}.yml up | tee output.txt

    - name: "Check if the log contains '[listener]: I heard: [Hello World' string"
      run: "if [[ $(grep '\[listener\]: I heard: \[Hello World' output.txt | wc -l) -eq 0 ]]; then exit 1; fi"
