name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  
jobs:
  start-discovery-server:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy Fast DDS Discovery Server
      run: |
        trap 'echo stopped without error' SIGTERM
        echo JOINCODE=${{ secrets.HUSARNET_JOINCODE }} > .env
        timeout 60 docker-compose -f docker-compose.discovery-server.yml up
        echo $?
        
  start-listener:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
  
    - name: Deploy Listener
      run: |
        trap 'echo stopped without error' SIGTERM
        echo JOINCODE=${{ secrets.HUSARNET_JOINCODE }} > .env
        timeout 60 docker-compose -f docker-compose.listener.yml up
        echo $?
      
  start-talker:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy Talker
      run: |
        trap 'echo stopped without error' SIGTERM
        echo JOINCODE=${{ secrets.HUSARNET_JOINCODE }} > .env
        timeout 60 docker-compose -f docker-compose.talker.yml up
        echo $?
